nohup python "/Users/witchpuff/Desktop/[MechanInterp]Time_tokens/neuron_patch.py" --token_len 1 --digit 0 --token_pos 3 > 'neuron103' 2>&1 &
nohup python "/Users/witchpuff/Desktop/[MechanInterp]Time_tokens/neuron_patch.py" --token_len 1 --digit 1 --token_pos 3 > 'neuron113' 2>&1 &
nohup python "/Users/witchpuff/Desktop/[MechanInterp]Time_tokens/neuron_patch.py" --token_len 1 --digit 2 --token_pos 3 > 'neuron123' 2>&1 &
nohup python "/Users/witchpuff/Desktop/[MechanInterp]Time_tokens/neuron_patch.py" --token_len 1 --digit 3 --token_pos 3 > 'neuron133' 2>&1 &
nohup python "/Users/witchpuff/Desktop/[MechanInterp]Time_tokens/neuron_patch.py" --token_len 2 --digit 0 --token_pos 3 > 'neuron203' 2>&1 &
nohup python "/Users/witchpuff/Desktop/[MechanInterp]Time_tokens/neuron_patch.py" --token_len 2 --digit 1 --token_pos 3 > 'neuron213' 2>&1 &
nohup python "/Users/witchpuff/Desktop/[MechanInterp]Time_tokens/neuron_patch.py" --token_len 2 --digit 2 --token_pos 3 > 'neuron223' 2>&1 &
nohup python "/Users/witchpuff/Desktop/[MechanInterp]Time_tokens/neuron_patch.py" --token_len 2 --digit 3 --token_pos 3 > 'neuron233' 2>&1 &
nohup python "/Users/witchpuff/Desktop/[MechanInterp]Time_tokens/neuron_patch.py" --token_len 2 --digit 0 --token_pos 4 > 'neuron204' 2>&1 &
nohup python "/Users/witchpuff/Desktop/[MechanInterp]Time_tokens/neuron_patch.py" --token_len 2 --digit 1 --token_pos 4 > 'neuron214' 2>&1 &
nohup python "/Users/witchpuff/Desktop/[MechanInterp]Time_tokens/neuron_patch.py" --token_len 2 --digit 2 --token_pos 4 > 'neuron224' 2>&1 &
nohup python "/Users/witchpuff/Desktop/[MechanInterp]Time_tokens/neuron_patch.py" --token_len 2 --digit 3 --token_pos 4 > 'neuron234' 2>&1 &